version: '3.7'

services:
  postgres:
    image: postgres:latest
    hostname: postgres_db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - golang_backend_network
    
  app:
    build: .
    hostname: golang_app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - golang_backend_network

volumes:
  postgres_data:

networks:
  golang_backend_network:
    external: true